export enum CategoriaLugarEnum {
    PANADERIA = "PANADERIA",
    BAR = "BAR",
    CAFETERIA = "CAFETERIA",
    RESTAURANTE = "RESTAURANTE",
    DISCOTECA = "DISCOTECA",
    OTRO = "OTRO",
    SUPERMERCADO = "SUPERMERCADO",
    TIENDA = "TIENDA",
    PIQUETEADERO = "PIQUETEADERO"
}